### ISSUE TITLE
Area param explanation?

### ISSUE THREAD

**Issue by dyerrington** [tabulapdf/tabula-extractor#100]
I'm curious what the area param is about:
```
        --area, -a <s>:   Portion of the page to analyze
                          (top,left,bottom,right). Example: --area
                          269.875,12.75,790.5,561. Default is entire page
```

Is it like like?

![image](https://cloud.githubusercontent.com/assets/2257834/8419049/e2ae7dd0-1e6b-11e5-9c42-76744c02d3be.png)

Thanks!

**Comment by jazzido** [comment]
it would be like this:
  - `top == y`
  - `left == x`
  - `bottom == y + h`
  - `right == x + w`

**Comment by dyerrington** [comment]
Thanks for clarifying.  Also, for anyone else that may be having this issue and have arrived here via search, if you're importing into photoshop, it will scale the size making the dimensions useless in this application.

**Comment by jazzido** [comment]
There are some pointers on this wiki page, too: https://github.com/tabulapdf/tabula-extractor/wiki/Using-the-command-line-tabula-extractor-tool
