### ISSUE TITLE
Field in form

### ISSUE THREAD

**Issue by Begood38** [tabulapdf/tabula-extractor#106]
Hi 

In the csv file all the form field from my pdf file are not extracted !!!

Thanks

**Comment by jeremybmerrill** [comment]
Please make sure that any ruling lines in your PDF are fully-contained in your selection. Or give us more info (including the output and the PDF) so we can help you more.

**Comment by Begood38** [comment]
Thanks for your answer.
I am sure and you will find PDF


Hereafter what I run
tabula e:\Temp\Test\RESA_810.pdf -a 700,30,200,650 --pages all -o e:\Temp\Test\RESA_810.csv

[RESA_810.pdf](https://github.com/tabulapdf/tabula-extractor/files/96740/RESA_810.pdf)

Hereafter the output
![image](https://cloud.githubusercontent.com/assets/16750445/12435842/61fdfc10-bf10-11e5-87c0-72b0baab4979.png)

Thanks in advance

**Comment by Begood38** [comment]
NoBody can help me on this topic !!!!

**Comment by jazzido** [comment]
Hi @Begood38,

Unfortunately, Tabula does not yet support extracting the contents of form fields. As you notice, the *Code*, *Produit* and *Qté* fields are correctly recognized. The rest of the columns, being form fields, will not be seen by Tabula.

Thanks.

**Comment by Begood38** [comment]
Thanks @jazzido for your answer
Your code is very useful. Do you think it could be possible to update it in order to be able to extract contents of form fields in near future ? Have you test it on Android with Ruboto IRB ?
Thanks a lot for your answer
Best regards
