### ISSUE TITLE
Warning message: `Failed to load class "org.slf4j.impl.StaticLoggerBinder".`

### ISSUE THREAD

**Issue by mhkeller** [tabulapdf/tabula-extractor#94]
I followed the instructions from [here](https://github.com/tabulapdf/tabula-extractor/wiki/Using-the-command-line-tabula-extractor-tool#using-rbenv) with the addition that instead of `rbenv install` for number 2, I ran `rbenv install jruby-1.7.15` since that line just printed the rbenv install help text and number 4 was then telling me I didn't have jruby installed. 

IHNIWID but that seemed to work except when I run `tabula --help` I get these three warning lines before the text. I'm running OS X 10.9.5. 

````
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tabula helps you extract tables from PDFs

Usage:
       tabula [options] <pdf_file>
where [options] are:
  -p, --pages=<s>           Comma separated list of ranges, or all. Examples:
                            --pages 1-3,5-7, --pages 3 or --pages all. Default
                            is --pages 1 (default: 1)
  -a, --area=<s>            Portion of the page to analyze
                            (top,left,bottom,right). Example: --area
                            269.875,12.75,790.5,561. Default is entire page
  -c, --columns=<s>         X coordinates of column boundaries. Example
                            --columns 10.1,20.2,30.3
  -s, --password=<s>        Password to decrypt document. Default is empty
                            (default: )
  -g, --guess               Guess the portion of the page to analyze per page.
  -d, --debug               Print detected table areas instead of processing.
  -f, --format=<s>          Output format (CSV,TSV,HTML,JSON) (default: CSV)
  -o, --outfile=<s>         Write output to <file> instead of STDOUT (default:
                            -)
  -r, --spreadsheet         Force PDF to be extracted using spreadsheet-style
                            extraction (if there are ruling lines separating
                            each cell, as in a PDF of an Excel spreadsheet)
  -n, --no-spreadsheet      Force PDF not to be extracted using
                            spreadsheet-style extraction (if there are ruling
                            lines separating each cell, as in a PDF of an Excel
                            spreadsheet)
  -i, --silent              Suppress all stderr output.
  -u, --use-line-returns    Use embedded line returns in cells. (Only in
                            spreadsheet mode.)
  -v, --version             Print version and exit
  -h, --help                Show this message
````

It seems like I don't have these bindings installed or I've got a path issue with jruby, which might be something to sort out on my end / unrelated to tabula. Flagging here in case there's some extra line to add to the docs.

When I run tabula on a file, the output looks good.

**Comment by jazzido** [comment]
It's harmless, disregard.

@jeremybmerrill that's fixed in `HEAD`, right?

**Comment by jeremybmerrill** [comment]
Yep, just a couple weeks ago: https://github.com/tabulapdf/tabula-extractor/commit/ea07ee17c03eb7ec87d965b2c86decd2fc0a7525 . Didn't think it was enough to warrant publishing a new version of the gem.

Welcome to the tabula-extractor club, @mhkeller! 

("When it's your first night at tabula-extractor club, you _have to extract_")

**Comment by mhkeller** [comment]
It's great to be here @jeremybmerrill! I'm glad I could get in before the place got shut down.
